// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package org.example;

public interface changevalueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:changevalue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 i = 1;</code>
   */
  int getI();

  /**
   * <code>int32 j = 2;</code>
   */
  int getJ();

  /**
   * <code>string val = 3;</code>
   */
  java.lang.String getVal();
  /**
   * <code>string val = 3;</code>
   */
  com.google.protobuf.ByteString
      getValBytes();
}
