// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package org.example;

public interface logicalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:logical)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool ans = 1;</code>
   */
  boolean getAns();
}
