// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package org.example;

public interface oneindexOrBuilder extends
    // @@protoc_insertion_point(interface_extends:oneindex)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ar = 1;</code>
   */
  int getAr();
}
