// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package org.example;

public interface onlystringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:onlystring)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ar = 1;</code>
   */
  java.lang.String getAr();
  /**
   * <code>string ar = 1;</code>
   */
  com.google.protobuf.ByteString
      getArBytes();
}
