// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package org.example;

public interface tableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:table)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated string names = 2;</code>
   */
  java.util.List<java.lang.String>
      getNamesList();
  /**
   * <code>repeated string names = 2;</code>
   */
  int getNamesCount();
  /**
   * <code>repeated string names = 2;</code>
   */
  java.lang.String getNames(int index);
  /**
   * <code>repeated string names = 2;</code>
   */
  com.google.protobuf.ByteString
      getNamesBytes(int index);

  /**
   * <code>repeated string types = 3;</code>
   */
  java.util.List<java.lang.String>
      getTypesList();
  /**
   * <code>repeated string types = 3;</code>
   */
  int getTypesCount();
  /**
   * <code>repeated string types = 3;</code>
   */
  java.lang.String getTypes(int index);
  /**
   * <code>repeated string types = 3;</code>
   */
  com.google.protobuf.ByteString
      getTypesBytes(int index);
}
