// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package org.example;

public interface twoindexOrBuilder extends
    // @@protoc_insertion_point(interface_extends:twoindex)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ar1 = 1;</code>
   */
  int getAr1();

  /**
   * <code>int32 ar2 = 2;</code>
   */
  int getAr2();
}
