// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package org.example;

public interface unionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:union)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated string args = 2;</code>
   */
  java.util.List<java.lang.String>
      getArgsList();
  /**
   * <code>repeated string args = 2;</code>
   */
  int getArgsCount();
  /**
   * <code>repeated string args = 2;</code>
   */
  java.lang.String getArgs(int index);
  /**
   * <code>repeated string args = 2;</code>
   */
  com.google.protobuf.ByteString
      getArgsBytes(int index);
}
